const DEFAULT_SVG_XMLNS = "http://www.w3.org/2000/svg";
const DEFAULT_SVG_SIZE = 100;
const DEFAULT_SVG_VIEW_BOX = {
  x: 0,
  y: 0,
  width: DEFAULT_SVG_SIZE,
  height: DEFAULT_SVG_SIZE,
};
const DEFAULT_SVG_FILL = "none";
const DEFAULT_SVG_STROKE = "currentColor";
const DEFAULT_SVG_STROKE_WIDTH = 2;
const DEFAULT_SVG_STROKE_LINECAP = "round";
const DEFAULT_SVG_STROKE_LINEJOIN = "round";

export {
  DEFAULT_SVG_FILL,
  DEFAULT_SVG_SIZE,
  DEFAULT_SVG_STROKE,
  DEFAULT_SVG_STROKE_LINECAP,
  DEFAULT_SVG_STROKE_LINEJOIN,
  DEFAULT_SVG_STROKE_WIDTH,
  DEFAULT_SVG_VIEW_BOX,
  DEFAULT_SVG_XMLNS,
};
